#pragma once

#define MAIN_Version "44f6480"
#define KNX_Version "2.4.0+8e4c5bc"
#define MODULE_Common_Version "1.9.1+66bc4af"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 9
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 25
#define MODULE_LogicModule_Version "4.4.1+cd1b5cc"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 4
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 68
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_BinaryInput_Version "0.4.0+5048828"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 4
#define MODULE_BinaryInput_Version_Revision 0
#define MODULE_BinaryInput_ETS 4
#define MODULE_HardwareConfig_Version "1.0.0+51dc43e"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_Irrigation_Version "39b7dee"
#define MODULE_Meter_Version "1.0.0+4714c02"
#define MODULE_Meter_Version_Major 1
#define MODULE_Meter_Version_Minor 0
#define MODULE_Meter_Version_Revision 0
#define MODULE_Meter_ETS 16
